{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b66e25c8-f409-4023-80f8-074cbf274a65",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1 What is an Exception in python? write the difference between Exception and syntax error\n",
    "\n",
    "\n",
    "ANSWER) Exception is the module in python to handle the run time errors and helps the program to run further Whereas syntax error are identified while coding\n",
    "The synatx error occurs when the coding is not executed as per python standards. The syntax erroro cannot handle run time error but the exception handler does\n",
    "\n",
    "\n",
    "Q2 What happens when the exception is not handled?Explain with example\n",
    "\n",
    "ANSWER) When the exception is not handled then the program will be terminated immedietly\n",
    "\n",
    "Example: when the user enters the age in alphabets instead of integer then the program terminates\n",
    "age = int(input(\"enter the age\"))\n",
    "print(age)\n",
    "\n",
    "Q3 Which python statements are used to catch exceptions? explain with example\n",
    "\n",
    "The except is used to catch the exception. In the below example when the user is asked for a age and he enters age in \n",
    "alphabets instead of using integers, so the  ValueError exception handles the exception\n",
    "\n",
    "try:\n",
    "    age = int(input(\"enter the age\"))\n",
    "    print(age)\n",
    "except ValueError as E:\n",
    "    print(E)\n",
    "    \n",
    "Q4 Explain with example :\n",
    "\n",
    "a try and else\n",
    "b finally\n",
    "c raise\n",
    "\n",
    "try and else\n",
    "\n",
    "The funtnality or code for the desied outcome is written in try block\n",
    "\n",
    "The else block is executed everytime the try block is successful without any errors\n",
    "\n",
    "finally\n",
    "Finally will execute everytime irrespective of the eception handling results\n",
    "\n",
    "\n",
    "\n",
    "try:\n",
    "    age = int(input(\"enter the age\"))\n",
    "    print(age)\n",
    "except ValueError as E:\n",
    "    print(E)\n",
    "else:\n",
    "    print(\"Else will execute if try block is sucessful\")\n",
    "finally:\n",
    "    print(\"Finally will execute everytime irrespective of the eception handling results\")\n",
    "\n",
    "\n",
    "\n",
    "raise can be usued to trigger the exceptioins that is defined (example below)\n",
    "\n",
    "    \n",
    "(custom exception)\n",
    "class valage(Exception):\n",
    "    def __init__(self,message):\n",
    "        self.message=message\n",
    "        \n",
    "\n",
    "try:\n",
    "    \n",
    "    age=int(input(\"enter the age)\n",
    "    if age>100:\n",
    "        raise valage(\"Entered age is unatural, please enter the correct age\")\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "\n",
    "                  \n",
    "Q5 What are custom exceptions in python? why do we need custom exceptions? explain with example\n",
    "                  \n",
    "The custom exceptions lets the user to create the exceptions based on the application requirement\n",
    "In compiling, the coding standards are only checked, but there may be scenario where the user input standard may be correct but not the value level\n",
    "                  \n",
    "In below example user is asked to enter the age. when the user enter age more than 120. it is incorrect in the logical way. but correct on the type\n",
    "to hadle these errors we use custom exceptions\n",
    "                  \n",
    "                  \n",
    "(custom exception)\n",
    "class valage(Exception):\n",
    "    def __init__(self,message):\n",
    "        self.message=message\n",
    "        \n",
    "\n",
    "try:\n",
    "    \n",
    "    age=int(input(\"enter the age\n",
    "    if age>100:\n",
    "        raise valage(\"Entered age is unatural, please enter the correct age\")\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "\n",
    "                  \n",
    "Q6 create a custom exception class use this class to handle an exception\n",
    "                  \n",
    "                  \n",
    "(custom exception)\n",
    "class valage(Exception):\n",
    "    def __init__(self,message):\n",
    "        self.message=message\n",
    "        \n",
    "\n",
    "try:\n",
    "    \n",
    "    age=int(input(\"enter the age\n",
    "    if age>100:\n",
    "        raise valage(\"Entered age is unatural, please enter the correct age\")\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "\n",
    "                  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "e4e3e2b5-746a-45b2-89c4-0e2b196a7938",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "enter the age dcc\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "invalid literal for int() with base 10: 'dcc'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    age = int(input(\"enter the age\"))\n",
    "    print(age)\n",
    "except ValueError as E:\n",
    "    print(E)\n",
    "    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
